// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicBandsAPI_Project.Services;

namespace MusicBandsAPI_Project.Migrations
{
    [DbContext(typeof(MusicBandsDbContext))]
    [Migration("20210217080712_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MusicBandsAPI_Project.Models.Band", b =>
                {
                    b.Property<int>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BandWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BandId");

                    b.ToTable("Bands");
                });

            modelBuilder.Entity("MusicBandsAPI_Project.Models.Release", b =>
                {
                    b.Property<int>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ReleaseId");

                    b.HasIndex("BandId")
                        .IsUnique();

                    b.HasIndex("ReleaseTypeId")
                        .IsUnique();

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("MusicBandsAPI_Project.Models.ReleaseType", b =>
                {
                    b.Property<int>("ReleaseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ReleaseTypeId");

                    b.ToTable("ReleaseTypes");
                });

            modelBuilder.Entity("MusicBandsAPI_Project.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("AwardReceived")
                        .HasColumnType("bit");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("SongId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("MusicBandsAPI_Project.Models.Release", b =>
                {
                    b.HasOne("MusicBandsAPI_Project.Models.Band", "Band")
                        .WithOne("Release")
                        .HasForeignKey("MusicBandsAPI_Project.Models.Release", "BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicBandsAPI_Project.Models.ReleaseType", "ReleaseType")
                        .WithOne("Release")
                        .HasForeignKey("MusicBandsAPI_Project.Models.Release", "ReleaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("ReleaseType");
                });

            modelBuilder.Entity("MusicBandsAPI_Project.Models.Song", b =>
                {
                    b.HasOne("MusicBandsAPI_Project.Models.Release", "Release")
                        .WithMany("Songs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("MusicBandsAPI_Project.Models.Band", b =>
                {
                    b.Navigation("Release");
                });

            modelBuilder.Entity("MusicBandsAPI_Project.Models.Release", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicBandsAPI_Project.Models.ReleaseType", b =>
                {
                    b.Navigation("Release");
                });
#pragma warning restore 612, 618
        }
    }
}
